### ISSUE TITLE
Terrain clipping too close

### ISSUE THREAD

**Issue by faculezcano** [Zylann/godot_heightmap_module#8] opened 2017-11-03 18:52 UTC
I create a heightmap with a raw file, the terrain is clipping too close and it seams that has to do with the camera pitch, when i watch to the bottom it doesnt clip.

![captura de pantalla_2017-11-03_15-46-46](https://user-images.githubusercontent.com/5156989/32390891-e6c9cacc-c0ae-11e7-9eee-0e0731806b69.png)

Thanks!

**Comment by Zylann** [comment] 2017-11-03 20:06
I know about this bug for a while, and there is no way to fix it... until the first feature of this list gets done in Godot Engine ^^" ==> https://github.com/godotengine/godot/issues/9046

The cause is basically that the module renders terrain patches by using shader displacement, but it creates a difference between the AABB of the mesh used (a flat plane with optional seams) and the visual result. The Godot renderer then fails to cull patches properly...

Some advice:
I see your filesystem contains heightmaps under the `*.tres` format. I would not recommend it, because heightmaps are comparable to images in terms of file size, text format is really suboptimal for them (I don't even remember if I implemented support for .tres).
Prefer using the `.heightmap` format, which is smaller in size and faster to load ;)

**Comment by faculezcano** [comment] 2017-11-03 22:04
I figured that out after posting the issue! There is no other way to displace the plane? like accessing the mesh data?

**Comment by Zylann** [comment] 2017-11-03 22:06
That's how the module worked before, every patch had its own mesh, but shader displacement ended up being faster, and costs less memory.

**Comment by faculezcano** [comment] 2017-11-03 22:18
Oh i see, do you even know where to start reading in the engine code, where the AABB is taking the original mesh data instead of the one displaced by the shader?

**Comment by Zylann** [comment] 2017-11-03 22:19
Somewhere in `VisualServer`, I don't know much the renderer implementation in detail. There is a struct that represents an instance, and what I need is an optional AABB on it that could be used by the culling system instead of falling back on the mesh resource in use.
Particles have this feature already (for the same reasons). I think if that feature is extended to all visual instances, Particles wouldn't need this specially on them.

**Comment by faculezcano** [comment] 2017-11-04 21:24
I was looking in the visualserver code and realice that `ArrayMesh` have a set_custom_aabb, and looking in the mesher code, when you create flat chunks [here](https://github.com/Zylann/godot_heightmap_module/blob/61d3855da74c30f657474a0cc082c656c30815fb/height_map_mesher.cpp#L25), what if you set a custom aabb with a height of max height to the `ArrayMesh`? I know it's not the properly solution but if it works is close to a fix.

**Comment by Zylann** [comment] 2017-11-04 21:35
It should not be here, make_flat_chunk() isn't actually called for each chunk update.
What it does is to generate a precalculated flat mesh (where all vertices have the same Y set to zero) for a given LOD, which will be *re-used* for many chunks, and will be displaced later in the shader per instance.
In other words, doing this on meshes is irrelevant, because the data source is a texture, not a mesh ;)

I am currently giving a try at adding per-instance custom AABBs to the Godot renderer. Once I have it, I will be able to set the AABB in here instead: https://github.com/Zylann/godot_heightmap_module/blob/61d3855da74c30f657474a0cc082c656c30815fb/height_map.cpp#L388

**Comment by Zylann** [comment] 2017-11-04 22:44
First tests look promising, no clipping anymore :)

**Comment by faculezcano** [comment] 2017-11-05 01:20
Nice! I'm glad to hear that, I'll wait for the commit

**Comment by Zylann** [comment] 2017-11-05 01:26
Might take some time, waiting for this first: https://github.com/godotengine/godot/pull/12645

**Comment by faculezcano** [comment] 2017-11-07 15:26
Hi @Zylann, is vertex painting working?

**Comment by Zylann** [comment] 2017-11-07 17:13
@faculezcano map painting code is there (with chunked undo/redo etc), but not used yet for texturing nor exposed in the UI. That's something I should work on next. If you have a concern about it, please open another issue.

**Comment by Zylann** [comment] 2017-11-14 00:01
I implemented AABB calculation here https://github.com/Zylann/godot_heightmap_module/commit/968fee413dc0fe33759c647085ace320aa6257b8, but it won't do anything because this line uses a feature Godot doesn't support yet: https://github.com/Zylann/godot_heightmap_module/commit/968fee413dc0fe33759c647085ace320aa6257b8#diff-6ecc4ee3460d2605411e9326fbfad3bdR91

All it needs is to have the PR I linked above to be merged, however that it is not scheduled to be in 3.0 :p

**Comment by faculezcano** [comment] 2017-11-14 04:24
Thank you so much @Zylann! Really is not being merged before nov 20? i am tracking this and the alpha close, if we push reduz to review your pr in the last issue of BETA APPROACHING? haha

**Comment by Zylann** [comment] 2017-11-14 10:16
I talked to him on IRC, it's not going for that version, but maybe the next

**Comment by darrylryan** [comment] 2017-11-14 16:04
I'm trying to get this working but got a bug:

![image](https://user-images.githubusercontent.com/3797848/32790100-66ce0414-c955-11e7-99f7-caf356cedb30.png)

**Comment by Zylann** [comment] 2017-11-14 18:01
@darrylryan did you get this immediately or after moving around?
Also, what is the resolution of your heightmap?

**Comment by darrylryan** [comment] 2017-11-14 19:13
@Zylann it did it as soon as i tried to create a new empty heightmap data

**Comment by Zylann** [comment] 2017-11-14 21:53
@darrylryan it should be fixed now

**Comment by darrylryan** [comment] 2017-11-15 12:56
@Zylann Its working! Thanks for the fix :) 👍

**Comment by Zylann** [comment] 2017-11-20 23:26
Clipping issue fixed in https://github.com/Zylann/godot_heightmap_module/commit/ae96cf5dcc806fa07ce59daad0864c043513095b

**Closed as completed by Zylann** 2017-11-20 23:26 UTC
Labels: bug
